# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

class Ui_Dialog_LoginPage(QDialog):
    def __init__(self):
        super(Ui_Dialog_LoginPage,self).__init__()
        self.setObjectName("Dialog_LoginPage")
        self.resize(487, 320)
        self.setWindowTitle("Dialog_LoginPage")

        self.setupUi()

    def setupUi(self):
        #Dialog_LoginPage.setObjectName("Dialog_LoginPage")
        #Dialog_LoginPage.resize(487, 320)
        self.secondarywidget = QtWidgets.QWidget()
        self.secondarywidget.setObjectName("secondarywidget")

        #Label 1
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(0, 30, 491, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setText("Login Page")

        #Label 2
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_2.setText("Please enter your name:")

        #Line edit name
        self.lineEdit_name = QtWidgets.QLineEdit(self)
        self.lineEdit_name.setGeometry(QtCore.QRect(20, 150, 451, 31))
        self.lineEdit_name.setClearButtonEnabled(False)
        self.lineEdit_name.setObjectName("lineEdit_name")

        #confirm push button
        self.pushButton_confirmLogin = QtWidgets.QPushButton(self)
        self.pushButton_confirmLogin.setGeometry(QtCore.QRect(100, 230, 111, 41))
        self.pushButton_confirmLogin.setObjectName("pushButton_confirmLogin")
        self.pushButton_confirmLogin.clicked.connect(self.login_clicked)
        self.pushButton_confirmLogin.setText("Login")
        
        #cancel push button
        self.pushButton_cancelLogin = QtWidgets.QPushButton(self)
        self.pushButton_cancelLogin.setGeometry(QtCore.QRect(280, 230, 111, 41))
        self.pushButton_cancelLogin.setObjectName("pushButton_cancelLogin")
        self.pushButton_cancelLogin.clicked.connect(self.cancel_login)
        self.pushButton_cancelLogin.setText("Cancel")
        self.username = ""

        #self.retranslateUi(Dialog_LoginPage)
        QtCore.QMetaObject.connectSlotsByName(self)

    def login_clicked(self):
        self.username = self.lineEdit_name.text()
        f = open('output.txt','a') #append
        f.write(self.username + '\n')
        f.close()
        self.done(1)

    def cancel_login(self):
        self.done(1)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_LoginPage = Ui_Dialog_LoginPage()
    Dialog_LoginPage.show()
    sys.exit(app.exec_())
