# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_LoginPage(object):
    def setupUi(self, Dialog_LoginPage):
        Dialog_LoginPage.setObjectName("Dialog_LoginPage")
        Dialog_LoginPage.resize(487, 320)
        self.label = QtWidgets.QLabel(Dialog_LoginPage)
        self.label.setGeometry(QtCore.QRect(0, 30, 491, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_LoginPage)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_name = QtWidgets.QLineEdit(Dialog_LoginPage)
        self.lineEdit_name.setGeometry(QtCore.QRect(20, 150, 451, 31))
        self.lineEdit_name.setClearButtonEnabled(False)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.pushButton_confirmLogin = QtWidgets.QPushButton(Dialog_LoginPage)
        self.pushButton_confirmLogin.setGeometry(QtCore.QRect(100, 230, 111, 41))
        self.pushButton_confirmLogin.setObjectName("pushButton_confirmLogin")
        self.pushButton_cancelLogin = QtWidgets.QPushButton(Dialog_LoginPage)
        self.pushButton_cancelLogin.setGeometry(QtCore.QRect(280, 230, 111, 41))
        self.pushButton_cancelLogin.setObjectName("pushButton_cancelLogin")

        self.retranslateUi(Dialog_LoginPage)
        QtCore.QMetaObject.connectSlotsByName(Dialog_LoginPage)

    def retranslateUi(self, Dialog_LoginPage):
        _translate = QtCore.QCoreApplication.translate
        Dialog_LoginPage.setWindowTitle(_translate("Dialog_LoginPage", "Dialog"))
        self.label.setText(_translate("Dialog_LoginPage", "Login Page"))
        self.label_2.setText(_translate("Dialog_LoginPage", "Please enter your name:"))
        self.pushButton_confirmLogin.setText(_translate("Dialog_LoginPage", "Login"))
        self.pushButton_cancelLogin.setText(_translate("Dialog_LoginPage", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_LoginPage = QtWidgets.QDialog()
    ui = Ui_Dialog_LoginPage()
    ui.setupUi(Dialog_LoginPage)
    Dialog_LoginPage.show()
    sys.exit(app.exec_())
