# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QDialog
from login import Ui_Dialog_LoginPage
import re


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super(Ui_MainWindow,self).__init__()
        self.setObjectName("MainWindow")
        self.resize(803, 600)
        self.setWindowTitle("MainWindow")

        self.setupUi()


    def setupUi(self):

        #Adding Widget functionality
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")

        #Adding the uploadManifest button
        self.pushButton_uploadManifest = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_uploadManifest.setGeometry(QtCore.QRect(330, 380, 141, 61))
        self.pushButton_uploadManifest.setObjectName("pushButton_uploadManifest")
        self.pushButton_uploadManifest.setText("Upload Manifest")

        #Adding label for Long Beach Port
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 150, 801, 91))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setText("Long Beach Port")

        #Adding label for CMS Software
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 230, 801, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_2.setText("Container Moving Software (CMS)")
        self.setCentralWidget(self.centralwidget)

        #Adding menubar
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 22))
        self.menubar.setObjectName("menubar")
        self.menuLogin = QtWidgets.QMenu(self.menubar)
        self.menuLogin.setObjectName("menuLogin")
        self.menuLogin.setTitle("Login")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuLogin.menuAction())
        self.LoginWindow = None # Set login window to none to show it has not been open yet

        #self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        self.pushButton_uploadManifest.clicked.connect(self.upload_manifest)
        self.menuLogin.aboutToShow.connect(self.show_login_window)

    def upload_manifest(self):
        name, _ = QtWidgets.QFileDialog.getOpenFileName(None, 'Open File', options=QtWidgets.QFileDialog.DontUseNativeDialog)
        file = open(name, 'r')
        x_coords, y_coords, weights, container_names = [], [], [], []

        for line in file:
            # Remove trailed newline character and brackets/paraenthesis from each line
            line = re.sub(r"[\([{})\]]", "", line)
            line = line.rstrip('\n')
            # Save x coordinate from current line and save rest of line in extra variable
            x, extra = line.lstrip().split(',', 1)
            # Save y coordinate current current line and save rest of line in extra variable
            y, extra = extra.lstrip().split(',', 1)
            # Save weight current current line and save rest of line in extra variable
            weight, extra = extra.lstrip().split(',', 1)
            # Save container name current line
            cont_name = extra.lstrip().split(',', 1)

            # Append values from current line to list
            x_coords.append(x)
            y_coords.append(y)
            weights. append(weight)
            container_names.append(cont_name)
        print(container_names)

    def show_login_window(self):
        if self.LoginWindow is None:
            self.LoginWindow = Ui_Dialog_LoginPage()
            #self.LoginWindow = QtWidgets.QDialog()
            #self.uiLogin = Ui_Dialog_LoginPage()
            #self.uiLogin.setupUi(self.LoginWindow)
            self.LoginWindow.show()
        else:
            self.LoginWindow.showEvent(self)


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = Ui_MainWindow()
    #ui = Ui_MainWindow()
    #ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
